export const THEME_REGISTRY = {
  'theme-home-decor': {
    id: 'theme-home-decor',
    
    name: 'Home Decor & Furniture',
    category: 'Home & Living',
    tagline: 'Timeless Artisanal Home Elegance',
    fontHeading: 'font-serif',
    bgPage: 'bg-[#faf8f5]',
    cardBg: 'bg-white',
    headerBg: 'bg-[#faf8f5]/90 backdrop-blur-md border-b border-[#e9e2d8]',
    bannerImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#936a4a',
    accentColor: '#d4a373',
    primaryBtn: 'bg-[#936a4a] hover:bg-[#7b563a] text-white shadow-sm',
    badgeStyle: 'bg-[#f4ece1] text-[#7b563a] border border-[#e4d5c3]',
    saleBadge: 'bg-[#c2784b] text-white',
    cartBtn: 'bg-[#936a4a] hover:bg-[#7b563a] text-white',
    navActive: 'text-[#936a4a] border-b-2 border-[#936a4a]',
    heroGradient: 'bg-gradient-to-br from-[#f4ece1] via-[#faf8f5] to-[#e7d5c2]',
    cardRadius: 'rounded-xl',
  },
  'theme-gadgets': {
    id: 'theme-gadgets',
    name: 'Gadgets & Electronics',
    category: 'Consumer Electronics',
    tagline: 'Engineered for Performance & Next-Gen Audio',
    fontHeading: 'font-sans font-bold',
    bgPage: 'bg-[#070b14]',
    cardBg: 'bg-[#101827] text-white border border-[#24344a]',
    headerBg: 'bg-[#070b14]/95 backdrop-blur-md border-b border-[#1d2a3c] text-white',
    bannerImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#0ea5e9',
    accentColor: '#67e8f9',
    primaryBtn: 'bg-cyan-500 hover:bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-900/30',
    badgeStyle: 'bg-cyan-950/80 text-cyan-300 border border-cyan-800',
    saleBadge: 'bg-gradient-to-r from-cyan-400 to-blue-500 text-slate-950 font-bold',
    cartBtn: 'bg-cyan-500 hover:bg-cyan-400 text-slate-950',
    navActive: 'text-cyan-300 border-b-2 border-cyan-400',
    isDark: true,
    heroGradient: 'bg-gradient-to-br from-[#080c16] via-[#101827] to-[#06354d]',
    cardRadius: 'rounded-lg',
  },
  'theme-fashion': {
    id: 'theme-fashion',
    name: 'Fashion & Apparel',
    category: 'Luxury Fashion',
    tagline: 'Modern Minimalist Runway Lookbook',
    fontHeading: 'font-serif tracking-tight',
    bgPage: 'bg-[#fafafa]',
    cardBg: 'bg-white',
    headerBg: 'bg-white/90 backdrop-blur-md border-b border-zinc-200',
    bannerImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#18181b',
    accentColor: '#a1a1aa',
    primaryBtn: 'bg-zinc-900 hover:bg-zinc-800 text-white uppercase tracking-wider text-xs font-semibold py-3',
    badgeStyle: 'bg-zinc-100 text-zinc-800 uppercase tracking-widest text-[10px]',
    saleBadge: 'bg-black text-white font-medium',
    cartBtn: 'bg-black hover:bg-zinc-800 text-white',
    navActive: 'text-black border-b-2 border-black font-semibold',
    heroGradient: 'bg-gradient-to-br from-zinc-100 via-white to-zinc-200',
    cardRadius: 'rounded-none',
  },
  'theme-bakery': {
    id: 'theme-bakery',
    name: 'Bakery & Cakes',
    category: 'Gourmet Pastry & Bakery',
    tagline: 'Baked with Love Fresh Every Morning',
    fontHeading: 'font-sans font-bold',
    bgPage: 'bg-[#fffaf9]',
    cardBg: 'bg-white border border-rose-100 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-md border-b border-rose-100',
    bannerImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#e11d48',
    accentColor: '#fda4af',
    primaryBtn: 'bg-rose-600 hover:bg-rose-700 text-white shadow-md shadow-rose-200',
    badgeStyle: 'bg-rose-50 text-rose-700 border border-rose-200',
    saleBadge: 'bg-rose-600 text-white',
    cartBtn: 'bg-rose-600 hover:bg-rose-700 text-white',
    navActive: 'text-rose-600 border-b-2 border-rose-600',
    heroGradient: 'bg-gradient-to-br from-rose-100 via-[#fffaf9] to-pink-200',
    cardRadius: 'rounded-2xl',
  },
  'theme-grocery': {
    id: 'theme-grocery',
    name: 'Supermarket & Grocery',
    category: 'Fresh & Organic Mart',
    tagline: 'Farm-Fresh Produce & Daily Essentials',
    fontHeading: 'font-sans font-semibold',
    bgPage: 'bg-[#f8faf8]',
    cardBg: 'bg-white border border-emerald-100 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-md border-b border-emerald-100',
    bannerImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#16a34a',
    accentColor: '#86efac',
    primaryBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white font-medium shadow-sm',
    badgeStyle: 'bg-emerald-50 text-emerald-800 border border-emerald-200',
    saleBadge: 'bg-emerald-600 text-white',
    cartBtn: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    navActive: 'text-emerald-700 border-b-2 border-emerald-600 font-bold',
    heroGradient: 'bg-gradient-to-br from-emerald-100 via-[#f8faf8] to-lime-100',
    cardRadius: 'rounded-xl',
  },
  'theme-car-accessories': {
    id: 'theme-car-accessories',
    name: 'Car Accessories',
    category: 'Automotive & Detailing',
    tagline: 'Pro Automotive Performance & Styling',
    fontHeading: 'font-sans font-black tracking-tight uppercase',
    bgPage: 'bg-[#121214]',
    cardBg: 'bg-[#1a1a1e] text-white border border-zinc-800',
    headerBg: 'bg-[#121214]/90 backdrop-blur-md border-b border-zinc-800 text-white',
    bannerImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#dc2626',
    accentColor: '#f87171',
    primaryBtn: 'bg-red-600 hover:bg-red-700 text-white uppercase font-bold tracking-wider',
    badgeStyle: 'bg-red-950/80 text-red-400 border border-red-800 text-xs',
    saleBadge: 'bg-red-600 text-white font-black',
    cartBtn: 'bg-red-600 hover:bg-red-700 text-white',
    navActive: 'text-red-500 border-b-2 border-red-500',
    isDark: true,
    heroGradient: 'bg-gradient-to-br from-[#121214] via-[#1a1a1e] to-[#450a0a]',
    cardRadius: 'rounded-lg',
  },
  'theme-toys': {
    id: 'theme-toys',
    name: 'Toy & Kids',
    category: 'Montessori & STEM Play',
    tagline: 'Sparking Wonder, Curiosity & Creative Play',
    fontHeading: 'font-sans font-bold',
    bgPage: 'bg-[#fcf8ff]',
    cardBg: 'bg-white border-2 border-purple-100 rounded-2xl shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-md border-b border-purple-100',
    bannerImage: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=1600&auto=format&fit=crop&q=80',
    primaryColor: '#7c3aed',
    accentColor: '#f59e0b',
    primaryBtn: 'bg-purple-600 hover:bg-purple-700 text-white rounded-xl shadow-md shadow-purple-200 font-bold',
    badgeStyle: 'bg-purple-100 text-purple-800 rounded-lg text-xs font-semibold',
    saleBadge: 'bg-amber-500 text-white font-bold rounded-lg',
    cartBtn: 'bg-purple-600 hover:bg-purple-700 text-white rounded-xl',
    navActive: 'text-purple-600 border-b-2 border-purple-600',
    heroGradient: 'bg-gradient-to-br from-purple-100 via-[#fcf8ff] to-amber-100',
    cardRadius: 'rounded-2xl',
  },
  'theme-whatsapp-store': {
    id: 'theme-whatsapp-store',
    name: 'WhatsApp Store',
    category: 'WhatsApp Commerce',
    tagline: 'Shop Smart on WhatsApp',
    isWhatsAppStore: true,
    fontHeading: 'font-sans font-bold',
    bgPage: 'bg-white',
    cardBg: 'bg-white',
    headerBg: 'bg-white border-b border-slate-100 shadow-sm',
    bannerImage: 'https://images.unsplash.com/photo-1611162617474-5b21e939e988?w=800&auto=format&fit=crop&q=80',
    heroImage: 'https://images.unsplash.com/photo-1611162617474-5b21e939e988?w=800&auto=format&fit=crop&q=80',
    heroGradient: 'bg-gradient-to-br from-[#dcf8e8] via-[#e8f8ef] to-[#f0fdf4]',
    productCard: 'bg-white border border-slate-100 shadow-sm hover:shadow-lg',
    primaryColor: '#25D366',
    accentColor: '#128C7E',
    primaryBtn: 'bg-[#25D366] hover:bg-[#20ba59] text-white shadow-sm',
    badgeStyle: 'bg-[#dcf8e8] text-[#128C7E] border border-[#b8e6cc]',
    saleBadge: 'bg-[#25D366] text-white',
    cartBtn: 'bg-[#25D366] hover:bg-[#20ba59] text-white',
    navActive: 'text-[#25D366] font-semibold',
    badgeText: 'WhatsApp Checkout',
    heroTextColor: 'text-slate-900',
    cardRadius: 'rounded-2xl',
  },
};

export const getThemeConfig = (themeId) => {
  const theme = THEME_REGISTRY[themeId] || THEME_REGISTRY['theme-home-decor'];
  return {
    heroGradient: 'bg-gradient-to-br from-slate-800 to-slate-950',
    heroImage: theme.bannerImage,
    productCard: `${theme.cardBg} border border-slate-200/60 shadow-sm hover:shadow-md`,
    badgeText: 'Special Collection',
    ...theme,
  };
};
